kemudi_web_v2/urls.py
from django.urls import path
from django.urls import include

from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

import django_pydenticon.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kemudi/', include('web.urls',namespace = 'web')),
    path('', RedirectView.as_view(url='/kemudi/', permanent=False)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('identicon/',django_pydenticon.urls.get_patterns()),
    #url(r'^blog/category/(?P<slug>[^\.]+).html','web.blogpost.views.view_category',name='view_blog_category'),

]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('blog/', views.blog.as_view(), name='blog'),
    path('blog/post/<slug:slug>', views.blogpost.as_view(), name='blog-post'),
    path('member/', views.member.as_view(), name='member'),
    path('atribut_lisensi/', views.lisensi.as_view(), name='lisensi'),
]

web/models.py
from django.db import models
from datetime import date
from ckeditor_uploader.fields import RichTextUploadingField
#from django.db.models import permalink
from django.urls import reverse
import uuid

# Create your models here.

class Blogdb(models.Model):
    judul = models.CharField(max_length = 50)
    konten = RichTextUploadingField()
    tanggal = models.DateTimeField('tanggal')
    dipost = models.DateField(db_index=True, auto_now_add=True)
    kategori = models.ForeignKey('web.Kategori',null=True,on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True,null=True)
    fotofitur = models.FileField(upload_to="upload/fitur/",blank=True)
    
    def __str__(self):
        return self.judul
    
    def get_absolute_url(self):
        return reverse('web:blog-post', args=[str(self.slug)])
    class Meta:
        verbose_name_plural = "Blog Content"
        ordering = ['-tanggal']


class Kategori(models.Model):
    kategori = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    
    def __str__(self):
        return self.kategori
    
#    @permalink
    def get_absolute_url(self):
        return reverse('web:kategori', args=[str(self.id)])
    class Meta:
        verbose_name_plural = "List Kategori"

class Anggota(models.Model):
    nama = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    pgp = models.TextField(max_length=5000,null=True,blank=True)
    nomor = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    

web/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView
from django.views.generic import DetailView
from django.views.generic import ListView

from .models import Blogdb,Anggota
# Create your views here.

class index(TemplateView):
    template_name = 'web/index.html'
    
    def get_context_data(self,**kwargs):
        context = super(index,self).get_context_data(**kwargs)
        context['lastfive'] = Blogdb.objects.order_by('-pk')[:5]
        return context
    
class blog(ListView):
    model = Blogdb
    template_name = 'web/update.html'
    
class blogpost(DetailView):
    model = Blogdb
    template_name = 'web/post.html'
    
class member(ListView):
    model= Anggota
    template_name = 'web/anggota.html'

class lisensi(TemplateView):
    template_name = 'web/lisensi.html'

web/templates/web/anggota.html
{% extends 'web/main.html' %}
{% block content %}
</br>
</br>
</br>
</br>
</br>
<div class="container">
<div class="row">
{% for anggota in anggota_list %}
<div class="col-md-4">
<img src="{% url 'django_pydenticon:image' anggota.email %}"/>
</div>
<div class="col-md-8">
<h2>{{ anggota.email }}</h2>
<hr>
<h2>{{ anggota.nomor }}</h2>
<hr>
 <div class="form-group">
  <label for="comment">Public Key:</label>
  <textarea class="form-control" rows="5" id="comment">{{ anggota.pgp }}</textarea>
</div> 
</div>
<div class="col-md-12">
<hr>
</div>
{% endfor %}
</div>
</div>
{% endblock content %}

web/templates/web/index.html
{% extends 'web/main.html' %}
{% load static %}
    {% block datalayer %}
    'konten':'singlepage',
    {% endblock datalayer %}
{% block content %}
<script src="{% static 'web/js/slide.js' %}"></script>
</br>
</br>
</br>
</br>
</br>

<div class="container">
<div class="row">
<div class="col-md" align="center">
<a href ="https://kelaskita.com/kemudi" target = "_blank">
<img src="{% static 'web/images/kelas_online.png' %}" width=200px>
<p class="title attn">Kelas Online</p>
</a>
</div>
<div class="col-md" align="center">
<a href="{% url 'web:index' %}#modul">
<img src="{% static 'web/images/modul.png' %}" width=200px>
<p class="title attn">Download Modul</p>
</a>
</div>
<div class="col-md" align="center">
<a href="#">
<img src="{% static 'web/images/pelatihan.png' %}" width=200px>
<p class="title attn">Pelatihan</p>
</a>
</div>
<div class="col-md" align="center">
<a href="https://forms.zohopublic.com/kemudixyz/form/KontakKemudi/formperma/jYuFFIgyu6hYZSMo8-8O9mcC-lwhRrsCf0LjDSFXKF4" target="_blank">
<img src="{% static 'web/images/kerjasama.png' %}" width=200px>
<p class="title attn">Kerjasama dengan Kemudi</p>
</a>
</div>
</div>
<hr>
<a id="tentang"></a>
</br>
</br>
</br>
</br>
</br>
<div class="container-fluid fadeIn">
<div class="title text-center attn">
<h1>Tentang</h1>
</div>
</div>

</br>
</br>

<div class="container">
<p>
Internet layaknya jalanan yang bisa dilalui dengan mengemudikan berbagai jenis kendaraan untuk mencapai berbagai tujuan. Seperti jalanan yang punya banyak pilihan juga hambatan, mengemudi di internet juga memerlukan pengetahuan dan keterampilan supaya tidak jatuh, terserempet, dan salah jalan.
</p>

<p>
Aturan-aturan terkait internet yang tidak matang, online hate speech, cyberbullying, predator anak, dan berbagai masalah lainnya yang setiap hari mengancam para pengguna internet sudah membalap jauh tingkat kesiapan para penggunanya, terutama anak muda hari ini yang sudah mengenal internet sejak kanak-kanak (digital natives). Kesiapan yang kami maksud adalah kesiapan memegang kendali penuh dalam menggunakan internet, bukan sekadar berhenti menjadi konsumen yang tak mau tahu. Sehingga, alih-alih memegang kendali, pengguna internet pun malah dikendalikan dan salah arah.
</p>
</div>

<a  id="update"></a>
</br>
</br>
</br>
</br>
</br>

<!--
<div class="container-fluid fadeIn">
<div class="title text-center attn">
<h1>Aktivitas</h1>
</div>
</br>
</br>
</div>
 <div class="slideshow-container">
{% for blog in lastfive %}
  <div class="mySlides">
    <a href="{{ blog.get_absolute_url }}">
    <div class="text-center"><font size="6">{{ blog.judul }}</font></div>
    </a>
  </div>
{% endfor %}
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div> 
<br>

<div style="text-align:center">
{% for dot in lastfive %}
  <span class="dot" onclick="currentSlide({{ dot.pk }})"></span>
{% endfor %}
</div> 
-->

</br>
</br>

<a id="modul"></a>
</br>
</br>
</br>
</br>
</br>

<div class="container-fluid fadeIn">
<div class="title text-center attn">
<h1>Modul</h1>
</div>
</div>

</br>
</br>

<div class="container">

<div class="row">
<div class="media col-md">
<a class="d-md-flex mb-5" href="media/uploads/modul/[lores] modul 1 EBookModulKEMUDI.pdf" target="_blank"> 
<img class ="mr-3" src="media/uploads/modul/modul 1.jpg" width=40% height=40% >
<div class="media-body">
“Internet dan HAM” bertujuan untuk mengkaji dan membahas lebih dalam mengenai kaitan antara Hak Asasi Manusia dalam mendorong demokratisasi dan terwujudnya pemerintahan yang terbuka. Bab ini akan membahas kaitan antara hak-hak asasi warga negara seperti hak untuk berekspresi, hak untuk bebas dari rasa takut dan ancaman, juga hak atas perlindungan privasi online, serta isu-isu lain terkait HAM dan internet di Indonesia. 
</div>
</div>
</a>
<div class="media col-md">
<a class="d-md-flex mb-5" href="media/uploads/modul/[lores] modul 2 EBookModulKEMUDI.pdf" target="_blank">
<img class ="mr-3" src="media/uploads/modul/modul 2.jpg" width=40% height=40% >
<div class="media-body">
Demokrasi digital merupakan sebuah konsep yang memiliki makna multi-tafsir: beberapa diantaranya adalah demokrasi digital dapat berarti demokrasi di ranah digital dan demokrasi yang dilakukan melalui medium digital. Penafsiran ini sepenuhnya masih terbuka mengingat era digital baru benar-benar terwujud di awal abad ke 21. Namun untuk memahami makna tersebut kita perlu membedah kembali makna masing-masing kata yang membentuk kata demokrasi digital itu sendiri.
</div>
</div>
</a>
</div>

</br>

<div class="row">
<div class="media col-md">
<a class="d-md-flex mb-5" href="media/uploads/modul/[lores] modul 3 EBookModulKEMUDI.pdf" target="_blank">
<img class ="mr-3" src="media/uploads/modul/modul 3.jpg" width=40% height=40% >
<div class="media-body">
Kelas ini bertujuan untuk mengenalkan netsiswa mengenai prinsip dasar pengelolaan internet, bahwa internet milik banyak orang dan setiap orang punya peran dalam membentuk masa depan internet.
</div>
</div>
</a>

<div class="media col-md">
<a class="d-md-flex mb-5" href="media/uploads/modul/[lores] modul 4 EBookModulKEMUDI.pdf" target="_blank">
<img class ="mr-3" src="media/uploads/modul/modul 4.jpg" width=40% height=40% >
<div class="media-body">
Kelas ini akan memamparkan bagaimana sebenarnya anak muda bisa menjaga privasi dan keamanannya ketika sedang menggunakan internet. Disajikan dalam beberapa bagian yang disertai juga dengan eksperimen.
</div>
</div>
</a>
</div>

</br>

<div class="row">

<div class="media col-md">
<a class="d-md-flex mb-5" href="media/uploads/modul/[lores] modul 5 EBookModulKEMUDI.pdf" target="_blank">
<img class ="mr-3" src="media/uploads/modul/modul 5.jpg" width=40% height=40% >
<div class="media-body">
Kelas ini akan menjelaskan bagaimana anak muda pada era digital ini dapat melakukan aktivisme dengan memanfaatkan teknologi yang ada. Belajar dari beberapa contoh kasus serta dengan menjawab pertanyaan-pertanyaan yang diberikan.
</div>
</div>
</a>
</br>
</br>
</br>
<div class="media col-md">
<div class="media-body">
</div>
</div>

</div>

</div>

<a  id="rekan"></a>
</br>
</br>
</br>
</br>
</br>

<div class="container-fluid fadeIn">
<div class="title text-center attn">
<h1>Rekan</h1>
</div>
</div>

</br>
</br>

<div class="container">
<div class="row">
<div class="col-md" align="center">
<img src="media/uploads/rekan/f_logo_RGB-Blue_512.png" width=200px>
</div>
<div class="col-md" align="center">
<img src="media/uploads/rekan/LOGO HMJ UNPAD-ok.png" width=200px>
</div>
<div class="col-md" align="center">
<img src="media/uploads/rekan/LOGO HIMAKOM UNAIR SURABAYA.png" width=200px>
</div>
</div>

</br>

<div class="row">
<div class="col-md" align="center">
<img src="media/uploads/rekan/LOGO Kosmik - UNHAS MAKASSAR.png" width=200px>
</div>
<div class="col-md" align="center">
<img src="media/uploads/rekan/logo pamflet.jpg" width=200px>
</div>
<div class="col-md" align="center">
<img src="" width=200px>
</div>
</div>

</br>

<div class="row">
<div class="col-md" align="center">
<img src="" width=200px>
</div>
<div class="col-md" align="center">
<img src="" width=200px>
</div>
<div class="col-md" align="center">
<img src="" width=200px>
</div>
</div>
</div>

<a id="medsos"></a>
</br>
</br>
</br>
</br>
</br>

<div class="container-fluid fadeIn">
<div class="title text-center attn" >
<h1>Media Sosial</h1>
</div>
</div>

</br>
</br>


<div class="container" >
<div class="row">
<div class="col-md" align="center">
<a gtm="gtm_fb" href="https://facebook.com/kelaskemudi" target="_blank">
<i class="fa fa-facebook-official" aria-hidden="true" style="color:#68c4be;font-size:150px"></i>
</br>
facebook
</a>
</div>
<div class="col-md" align="center">
<a gtm="gtm_ig" href="https://www.instagram.com/kemudi/" target="_blank">
<i class="fa fa-instagram" aria-hidden="true" style="color:#68c4be;font-size:150px"></i>
</br>
instagram
</a>
</div>

<div class="col-md" align="center">
<a gtm="gtm_tw" href="https://twitter.com/kemudi_" target="_blank">
<i class="fa fa-twitter-square" aria-hidden="true" style="color:#68c4be;font-size:150px"></i>
</br>
twitter
</a>
</div>
</div>
</div>


{% endblock content %}

web/templates/web/lisensi.html
{% extends 'web/main.html' %}
{% block content %}
</br>
</br>
</br>
</br>
<ul>
<li><div>Icons made by <a href="https://www.flaticon.com/authors/eucalyp" title="Eucalyp">Eucalyp</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
</ul>
{% endblock content %}

web/templates/web/main.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}KEMUDI ::: Kelas Muda Digital{% endblock title%}</title>
        <script>
            dataLayer = [{
                'dataLayer' : 'true',
                {% block dataLayer %}
                {% endblock dataLayer %}
            }]
        </script>

        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-K2TJNCZ');</script>
        <!-- End Google Tag Manager -->
        <!-- Hotjar Tracking Code for kemudi.xyz -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:846433,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
    <!-- bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <!-- end bootstrap scripts-->
    <script src="https://use.fontawesome.com/038ae275d4.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

        <!-- end bootstrap -->
    </head>

        <body>
            <!-- Google Tag Manager (noscript) -->
            <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K2TJNCZ"
            height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
            <!-- End Google Tag Manager (noscript) -->

            <div class = "container-fluid">

            <br>
            <br>

    <nav class="navbar navbar-expand-md fixed-top">
        <a gtm="gtm_logo_navbar" class= "navbar-brand brand" href="{% url 'web:index' %}"><img class = "navbrand" src={% static 'web/images/logo.png' %}></a>                
        <button gtm="gtm_menu_responsive" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars" style="color:#fff"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto attn">
                <li class="nav-item"><a gtm="gtm_tentang" class="nav-link" href="{% url 'web:index' %}#tentang">tentang</a></li>
                <li class="nav-item"><a gtm="gtm_update" class="nav-link" href="{% url 'web:blog' %}"><x style="color:#262262">aktivitas</x></a></li>
                <li class="nav-item"><a gtm="gtm_modul" class="nav-link" href="{% url 'web:index' %}#modul">modul</a></li>
                <li class="nav-item"><a gtm="gtm_rekan" class="nav-link" href="{% url 'web:index' %}#rekan">rekan</a></li>
                <li class="nav-item"><a gtm="gtm_medsos" class="nav-link" href="{% url 'web:index' %}#medsos">media sosial</a></li>
                <li class="nav-item"><a gtm="gtm_login" class="nav-link" href="{% url 'web:member' %}">anggota</a></li>

            </ul>
        </div>
    </nav>
            </div>
            <div class = "container-fluid">
            {% block content %}{% endblock content%}
            </div>
            <br>
            <br>

            <footer class="footer">
                <div class="container-fluid" style="background:#262262;color:#fff" align="center">
                <p><a href="http://kemudi.xyz/">
                         <img src="{% static 'web/main/KEMUDI_WHITE-01.png' %}" alt="KEMUDI" width=20%>
                       </a></p>    
                    <p class="brand pull-left"><p>Konten <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.id"><a gtm="gtm_cc" rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/deed.id" target="_blank"><img alt="Lisensi Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" width="100"></a> dikembangkan oleh <a gtm="gtm_gitlab" class="attn" href="https://gitlab.com/aps2201/kemudi" target="_blank" style="color:#fff">kemudi</a></p>
                    <p><a gtm="gtm_lisensi" href="{% url 'web:lisensi' %}" style="color:#fff">Atribut dan Lisensi</a></p>
                    </br>
                    </br>
                </div>
            </footer>
        </body>
</html>

web/templates/web/post.html
{% extends 'web/main.html' %}

    {% block dataLayer %}
    'author':'{{ User.username }}',
    'kategori':'{{ blogdb.kategori }}',
    'tanggal':'{{ blogdb.tanggal }}',
    'dipost':'{{ blogdb.dipost }}',
    'judul':'{{ blogdb.judul }}',
    'konten':'post',

    {% endblock dataLayer %}
{% block content %}
</br>
</br>
</br>
</br>
<div class="container">
    </br>
    <h1>{{ blogdb.judul }}</h1>
    <img src="{{ blogdb.fotofitur }}">
    {{ blogdb.konten|safe }}
    </br>
    <p class="text-center">kategori: {{ blogdb.kategori }} </p> 
    <p class="text-right"> <a gtm="gtm_update" href="{% url 'web:blog' %}"> <<- kembali</a></p>
</div>
{% endblock content %}

web/templates/web/update.html
{% extends 'web/main.html' %}

    {% block dataLayer %}
    'author':'{{User.username}}'
    {% endblock dataLayer %}

{% block content %}
</br>
</br>
</br>
</br>
<div class="container">
<h1>Aktivitas</h1>
</br>
{% if blogdb_list %}
{% for blog in blogdb_list %}
<ul>
<div class="media">
<img class = "pr-3" src="{{ blog.fotofitur }}" width=20%>
<div class = "media-body">
<h3>
<a href="{{ blog.get_absolute_url }}">{{ blog.judul }}</a>
</h3>
<p>{{blog.tanggal}}</p>
{% autoescape off %}
<p>{{ blog.konten|truncatewords:22}}</p>
{% endautoescape %}
</div>
</div>
</ul>
{% endfor %}
{% else %}
<p>Ga ada apa-apa<p>
{% endif %}
{% endblock content %}